const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Behaviors.Physics,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Plugins.Particles,
		C3.Plugins.gamepad,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Fade,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.gamepad.Cnds.IsButtonDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.gamepad.Cnds.OnButtonDown,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Behaviors.Physics.Acts.SetSteppingMode,
		C3.Plugins.Particles.Cnds.OnCreated,
		C3.Plugins.Particles.Acts.SetPosToObject,
		C3.Plugins.Particles.Acts.ZMoveToObject,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Behaviors.Physics.Acts.ApplyForceAtAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Particles.Acts.MoveAtAngle,
		C3.Plugins.Particles.Exps.X,
		C3.Plugins.Particles.Exps.Y,
		C3.Plugins.System.Acts.RestartLayout
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{Physics: 0},
	{Ground: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{PlayerCollision: 0},
	{PlayerGraphics: 0},
	{Keyboard: 0},
	{Ball: 0},
	{Area: 0},
	{Arrow: 0},
	{Trail: 0},
	{Smoke: 0},
	{Gamepad: 0},
	{Fade: 0},
	{Tutorial: 0},
	{InputLeft: 0},
	{InputRight: 0},
	{InputUp: 0},
	{InputDown: 0},
	{InputHorizontalAxis: 0},
	{InputVerticalAxis: 0}
];

self.InstanceType = {
	Ground: class extends self.ITilemapInstance {},
	PlayerCollision: class extends self.ISpriteInstance {},
	PlayerGraphics: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Ball: class extends self.ISpriteInstance {},
	Area: class extends self.ISpriteInstance {},
	Arrow: class extends self.ISpriteInstance {},
	Trail: class extends self.IParticlesInstance {},
	Smoke: class extends self.IParticlesInstance {},
	Gamepad: class extends self.IInstance {},
	Tutorial: class extends self.ISpriteFontInstance {}
}